FROM nextcloud

RUN apt-get update -y \
    && apt-get install -y ffmpeg \
    && rm -rf /var/lib/apt/lists  \
    && apt autoclean -y \
    && apt autoremove -y 


    
    
    
    
    
    
    
    
    
    
    
    
    
    
