[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/home/freefilesync/logs/supervisord.log
childlogdir=/home/freefilesync/logs/
logfile_maxbytes=10MB

[program:x11]
priority=0
command=/usr/bin/Xtigervnc -desktop "FreeFileSync" -localhost -rfbport 5900 -SecurityTypes None -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -SendCutText -AcceptCutText :0
autorestart=true
redirect_stderr=true

[program:easy-novnc]
priority=0
command=/usr/local/bin/easy-novnc --addr :8080 --basic-ui --host localhost --port 5900 --no-url-password --novnc-params "resize=remote"
autorestart=true
redirect_stderr=true

[program:openbox]
priority=1
command=/usr/bin/openbox
environment=DISPLAY=:0
autorestart=true
redirect_stderr=true

[program:tint2]
priority=1
command=/usr/bin/tint2 -c /opt/tint2.conf
environment=DISPLAY=:0
autorestart=true
redirect_stderr=true

[program:freefilesync]
priority=2
environment=DISPLAY=:0,HOME="/home/freefilesync"
directory=/home/freefilesync
command=/opt/freefilesync/Bin/FreeFileSync_x86_64 -Edit -DirPair /path1 /path2
autorestart=true
redirect_stderr=true
